name: Update Research Data

on:
  schedule:
    - cron: "0 0 * * *" # 毎日午前0時に実行
  workflow_dispatch: # 手動実行トリガー
  push:
    branches:
      - main # mainブランチにプッシュされた時に実行

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへのwrite権限を明示的に付与

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0

      - name: Regenerate poetry.lock
        run: poetry lock

      - name: Install dependencies
        run: poetry install --no-dev # 開発依存関係を除外

      - name: Update research data
        run: poetry run python scripts/fetch_researchmap.py

      - name: Deploy to page branch
        run: |
          # Git設定
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # 現在の変更を保存（pageブランチへのデプロイ用）
          git add _auto_contents/ _data/ poetry.lock

          # pageブランチが存在するか確認し、なければ作成
          git fetch origin
          if ! git ls-remote --heads origin page | grep page; then
            git checkout -b page
            git commit -m "Initial deployment to page branch"
            git push -u origin page
          else
            # 既存のpageブランチにデプロイ
            git checkout -b temp_deploy
            git fetch origin page
            git reset --hard origin/page
            
            # 更新したデータを適用
            git checkout FETCH_HEAD -- _auto_contents/ _data/ poetry.lock
            
            # 変更をコミット
            git add .
            git commit -m "Deploy updated research data (automated)" || echo "No changes to deploy"
            git push origin HEAD:page
          fi
