name: 研究業績更新

on:
  schedule:
    - cron: "0 0 * * *" # 毎日午前0時（UTC）に実行
  workflow_dispatch: # 手動実行用

jobs:
  update-research-data:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python環境セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Poetry インストール
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: 依存関係インストール
        run: |
          poetry install

      - name: ResearchMapデータ取得
        run: |
          poetry run python scripts/fetch_researchmap.py

      - name: 変更を確認してコミット
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/research_data.json _auto_contents/
          git diff --staged --quiet || git commit -m "研究データを自動更新 $(date +'%Y-%m-%d')"

      - name: 変更をプッシュ
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
